#!/bin/bash
# Edit tag on Dicom images
# Send Dicom files to xnat

url="https://xnat.vanderbilt.edu/xnat/data/projects/HEM1538"
PrjDir=/share4/hem1538/mayo-clinic-02/01-100-C3D1/

if [ "$#" -ne 1 ]; then
	echo "Incorrect number of arguments - expecting 1"
	echo "Usage : ./send_disk User_id"
else
	project_exist_check=$(curl -s -I -u $1 $url)
	if [[ $project_exist_check == HTTP/1.1\ 200* ]]; then
		echo "ok"	
	
		# Progress bar
		total_files=$(find $PrjDir/* -maxdepth 1 -type f | wc -l)

	#	echo -ne 'sending dcm files: ['
	#	for i in $(seq 1 $total_files); do echo -n ' '; done;
	#	echo -ne ']\r'
	#	python /share4/hyeonsoo/SegPipeline/comments.py $PrjDir
		find $PrjDir -type f -name '*.dcm' -exec python comments.py {} \; 
		find $PrjDir -type f -name '*.dcm' -exec python storescu.py -aec VandyXNAT xnat.vanderbilt.edu 8104 {} \;
	#	find $PrjDir -type f -name '3371280' -exec python storescu.py -aec VandyXNAT xnat.vanderbilt.edu 8104 {} \;
		#find $PrjDir -type f -name '*_v2' -delete
	else
		echo "project HEM1538 not found"
		echo "If the proejct is already existing, check your XNAT ID and PWD"
	fi
fi



